### ISSUE TITLE
Describe more clearly what is changed in comparison to original IPA

### ISSUE THREAD

**Issue by deinlandel** [russianGecko/IPA-Reloaded#1]
Hello!

It's very good that you decided to continue development of the original IPA, but it's very hard to understand what the differences are, because you haven't used github's forking mechanism.

Could you please describe in the readme what did you change/improve in the original IPA?

**Comment by mikegecko** [comment]
Unity changed where the Input and Display calls from UnityEngine.dll to UnityEngineCore.dll are made, so the injector simply needed the path names to be changed. ( I didn't fork because the original creator has not been active)
